steps:
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - 'git clone https://gitlab-token:$$GITHUB_TOKEN@${_REPO_URL} repo'
    entrypoint: bash
    secretEnv:
      - GITHUB_TOKEN
  - name: hashicorp/terraform
    args:
      - init
      - '-backend-config=bucket=${_TF_BACKEND_BUCKET}'
      - '-backend-config=prefix=${_TF_BACKEND_PREFIX}'
    dir: repo
  - name: hashicorp/terraform
    args:
      - plan
      - '-out=/workspace/tfplan-$BUILD_ID'
    dir: repo
  - name: hashicorp/terraform
    args:
      - apply
      - '-auto-approve'
      - /workspace/tfplan-$BUILD_ID
    dir: repo
substitutions:
  _TF_BACKEND_BUCKET: 'tf-state-${PROJECT_ID}'
  _TF_BACKEND_PREFIX: tf-state-prefix
  _GIT_REPO: $(body.project.git_http_url)
  _REPO_URL: '${_GIT_REPO##https://}'
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/github-access-token/versions/latest'
      env: GITHUB_TOKEN
